/* tslint:disable */
/* eslint-disable */
/**
 * Pill.City
 * API for an one-of-a-kind social network
 *
 * OpenAPI spec version: 0.0.1
 * Contact: feedback@pill.city
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface InlineResponse200
 */
export interface InlineResponse200 {
    /**
     * User's bearer token
     * @type {string}
     * @memberof InlineResponse200
     */
    accessToken: string;
    /**
     * In epoch seconds, when the bearer token will expire
     * @type {number}
     * @memberof InlineResponse200
     */
    expires: number;
}
