/* tslint:disable */
/* eslint-disable */
/**
 * Pill.City
 * API for an one-of-a-kind social network
 *
 * OpenAPI spec version: 0.0.1
 * Contact: feedback@pill.city
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { PollChoice } from './poll-choice';
/**
 * 
 * @export
 * @interface Poll
 */
export interface Poll {
    /**
     * Choices for this poll
     * @type {Array<PollChoice>}
     * @memberof Poll
     */
    choices?: Array<PollChoice>;
    /**
     * In epoch seconds, by when this poll will close. Default 0 meaning the poll will never close.
     * @type {number}
     * @memberof Poll
     */
    closeBySeconds?: number;
}
