/* tslint:disable */
/* eslint-disable */
/**
 * Pill.City
 * API for an one-of-a-kind social network
 *
 * OpenAPI spec version: 0.0.1
 * Contact: feedback@pill.city
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface CloudEmoticonEntry
 */
export interface CloudEmoticonEntry {
    /**
     * The emoticon
     * @type {string}
     * @memberof CloudEmoticonEntry
     */
    emoticon: string;
    /**
     * Description for the emoticon
     * @type {string}
     * @memberof CloudEmoticonEntry
     */
    description: string;
}
