/* tslint:disable */
/* eslint-disable */
/**
 * Pill.City
 * API for an one-of-a-kind social network
 *
 * OpenAPI spec version: 0.0.1
 * Contact: feedback@pill.city
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CloudEmoticonEntry } from './cloud-emoticon-entry';
/**
 * 
 * @export
 * @interface CloudEmoticonCategory
 */
export interface CloudEmoticonCategory {
    /**
     * The category name
     * @type {string}
     * @memberof CloudEmoticonCategory
     */
    name: string;
    /**
     * Emoticon entries for the category
     * @type {Array<CloudEmoticonEntry>}
     * @memberof CloudEmoticonCategory
     */
    entries: Array<CloudEmoticonEntry>;
}
