/* tslint:disable */
/* eslint-disable */
/**
 * Pill.City
 * API for an one-of-a-kind social network
 *
 * OpenAPI spec version: 0.0.1
 * Contact: feedback@pill.city
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { User } from './user';
/**
 * 
 * @export
 * @interface PollChoice
 */
export interface PollChoice {
    /**
     * Permanent ID for the poll choice
     * @type {string}
     * @memberof PollChoice
     */
    id: string;
    /**
     * Text content for the poll choice
     * @type {string}
     * @memberof PollChoice
     */
    content: string;
    /**
     * URL for the poll choice's media
     * @type {string}
     * @memberof PollChoice
     */
    media: string;
    /**
     * User who have voted for this poll choice
     * @type {Array<User>}
     * @memberof PollChoice
     */
    voters?: Array<User>;
}
