/* tslint:disable */
/* eslint-disable */
/**
 * Pill.City
 * API for an one-of-a-kind social network
 *
 * OpenAPI spec version: 0.0.1
 * Contact: feedback@pill.city
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface User
 */
export interface User {
    /**
     * The permanent short ID for the user
     * @type {string}
     * @memberof User
     */
    id: string;
    /**
     * In epoch seconds, when the user signed up
     * @type {number}
     * @memberof User
     */
    createdAtSeconds: number;
    /**
     * URL to the user's avatar
     * @type {string}
     * @memberof User
     */
    avatarUrl?: string;
    /**
     * User's choice of profile banner. The choices are defined on web frontend.
     * @type {string}
     * @memberof User
     */
    profilePic?: string;
    /**
     * User's displayed/regular name. Can be changed.
     * @type {string}
     * @memberof User
     */
    displayName?: string;
}
